### ISSUE TITLE
Not working with new azure pipelines (YAML) ?

### ISSUE THREAD

**Issue by B4rT45** [jessehouwing/vsts-ensure-tests#9]
pipeline.yaml
```
# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

<....>
build and run tests
<....>

- task: Ensure tests have executed.@0
  inputs:
    minNumOfExpectedTests: 3
```

When trying to run getting:

![image](https://user-images.githubusercontent.com/43419510/79485557-50fe6180-800d-11ea-894a-b81d00119911.png)

**Comment by jessehouwing** [comment]
This is a release gate/server task. you need to configure your job to run agentless. 

I think the syntax is 

```
jobs:
- job: Ensure tests
  pool: 'server'
  tasks:
    - task: Ensure tests have executed.@0
      inputs:
        minNumOfExpectedTests: 3
```
